Votre vie privée est importante pour CamerMarket et le serai toujours. Nous avons donc mis en point une politique de confidentialité qui couvre la façon dont nous recueillons, utilisons, divulguer, transférer et stocker vos informations. S'il vous plaît prendre un moment pour vous familiariser avec nos pratiques de confidentialité et laissez - nous savoir si vous avez des questions. 
En visitant CamerMaket, vous acceptez les pratiques décrites dans le présent avis de confidentialité.
Vue d'ensemble: 

Comment les renseignements personnels sur les clients sont utilisées?
Qu'est-ce que des renseignements personnels sur les clients ne fait CamerMarket Rassemblez?
Qu'en est-il des cookies?
Quelle est la précision des données personnelles fournies à CamerMarket?
Comment mes informations sont-elles sécurisées?
Exemples d'informations collectées
Quels sont vos droits?
1. Comment les informations personnelles sur les clients sont utilisées?
Les données utilisateur peuvent être partagés avec les fournisseurs CamerMarket pour améliorer le traitement des commandes et le service à la clientèle. Il peut également être utilisé à la fois pour la commercialisation des fins de recherche et de gestion de la relation client, étant précisé que certains de ces fournisseurs ne sont pas situés dans l'Union européenne. 

Ce qui est fait avec vos informations personnelles? 
Les données utilisateur recueillies nous aident à personnaliser notre site selon les souhaits et les préférences de chaque utilisateur. En vous offrant une expérience de surf le plus spontané et amical est notre priorité. Les données collectées sont uniquement à des fins statistiques et nous aident à:
Traiter les commandes
Fournir des produits et services
Traiter les paiements et de communiquer avec vous au sujet de vos commandes, des produits, des services et des offres promotionnelles
Conserver et mettre à jour notre base de données et de vos comptes avec nous
Proposer une expérience unique et ciblée de navigation
Prévenir et détecter les fraudes et les abus sur notre site
2. Qu'en est-il des cookies?
Les cookies sont des identificateurs uniques que nous transférons sur votre appareil pour permettre à nos systèmes de reconnaître votre appareil et pour fournir des fonctionnalités pour rendre votre expérience de navigation unique et ciblée. 

L'acceptation des cookies n'est pas une exigence pour visiter le site. Cependant , nous tenons à souligner que l'utilisation du «panier» fonctionnalité sur le site et la commande est possible uniquement avec l'activation des cookies. Les cookies sont de petits fichiers texte qui identifient votre ordinateur à notre serveur en tant qu'utilisateur unique lorsque vous visitez certaines pages du site et ils sont stockés par votre navigateur Internet sur le disque dur de votre ordinateur. Les cookies peuvent être utilisés pour reconnaître votre adresse de protocole Internet, vous gagnez du temps pendant que vous êtes sur, ou si vous voulez entrer, le Site. Nous utilisons uniquement les cookies pour votre commodité dans l' utilisation du site (par exemple de se rappeler qui vous êtes quand vous voulez modifier votre panier sans avoir à entrer de nouveau votre adresse e - mail) et non pour obtenir ou utiliser toute autre information sur vous ( par exemple la publicité ciblée). Votre navigateur peut être configuré pour ne pas accepter les cookies, mais cela limiterait votre utilisation du site. S'il vous plaît accepter notre assurance que notre utilisation des cookies ne contient pas de détails personnels ou privés et sont exempts de virus. 

3. Quelle est l'exactitude des données personnelles fournies à CamerMarket?
Vous déclarez et garantissez que vous êtes le propriétaire ou disposer des droits nécessaires sur le contenu que vous nous transmettez; que, à la date de sa transmission (i) le contenu est exact et vrai, (ii) l'utilisation du contenu ne contrevient à aucune de nos politiques et ne sera pas préjudiciable à une tierce partie (à savoir que le contenu ne soit pas diffamatoire) .

4. Comment sont sécurisés les Informations me concernant?
Il est important pour nous de vous protéger contre l' accès non autorisé à votre mot de passe et à votre ordinateur. Assurez - vous de vous déconnecter lorsque vous utilisez un ordinateur partagé. Nous travaillons pour protéger la sécurité de vos informations lors de la transmission en utilisant Secure Sockets Layer (SSL), qui crypte les informations que vous saisissez. Nous ne révélons que les quatre derniers chiffres de votre numéro de carte de crédit lors de la confirmation d' une commande. Bien sûr, nous transmettons le numéro de carte de crédit à la société de carte de crédit approprié pendant le traitement des commandes. 


5. Exemples d'informations collectées:
Les informations que vous nous donnez: Vous fournissez la plupart de ces informations lorsque vous effectuez une recherche, acheter, poste, participer à un concours ou d'un questionnaire, ou communiquer avec le service à la clientèle. Par exemple, vous fournissez des informations lorsque vous recherchez un produit; placer une commande par CamerMarket ou un de nos vendeurs tiers; fournir des informations sur votre compte (et vous pourriez avoir plus d'un si vous avez utilisé plus d'une adresse e-mail lors de l' achat avec nous) ou votre profil; communiquer avec nous par téléphone, e-mail, ou autrement; remplir un questionnaire ou un formulaire d'inscription au concours. À la suite de ces actions, vous pourriez nous fournir des informations telles que votre nom, adresse et numéros de téléphone; informations de carte de crédit; les gens à qui les achats ont été expédiés, y compris les adresses et numéro de téléphone; adresses e-mail de vos amis et d' autres personnes; le contenu des examens et des e-mails à nous; Description personnelle et photographie dans votre profil; et de l' information financière, y compris la sécurité sociale et les numéros de permis de conduire.

Informations automatiques: Des exemples de l'information que nous recueillons et analysons comprennent le protocole Internet (IP) utilisée pour connecter votre ordinateur à l'Internet; s'identifier; adresse e-mail; mot de passe; ordinateur et connexion des informations telles que le type de navigateur, la version, et le réglage de fuseau horaire, les types et les versions plug-in navigateur, système d'exploitation, et la plate - forme; acheter l' histoire, que nous regroupons parfois avec des informations similaires provenant d' autres clients pour créer des fonctionnalités telles que Meilleures ventes; Uniform Resource Locator (URL) clickstream complet, cependant, et de notre site Web, y compris la date et l' heure; numéro de témoin; produits que vous avez consultés ou recherchés; et le numéro de téléphone que vous avez l' habitude d'appeler notre numéro 800. Nous pouvons également utiliser les données du navigateur telles que les cookies, les cookies Flash (également connu sous le nom de Flash Local Shared Objects), ou des données similaires sur certaines parties de notre site Web pour la prévention de la fraude et d' autres fins. Au cours des visites , nous pouvons utiliser des outils logiciels tels que JavaScript afin de mesurer et de recueillir des informations de session, y compris les temps de réponse des pages, télécharger des erreurs, la durée des visites à certaines pages, page d' information d'interaction (comme le défilement, les clics et souris-overs), et méthodes utilisées pour naviguer loin de la page. Nous pouvons également recueillir des informations techniques pour nous aider à identifier votre appareil pour la prévention de la fraude et à des fins de diagnostic.

Mobile: La plupart des appareils mobiles de fournir aux utilisateurs la possibilité de désactiver les services de localisation. Très probablement, ces contrôles sont situés dans le menu de l'appareil de réglage. Si vous avez des questions sur la façon de désactiver les services de localisation de votre appareil, nous vous recommandons de contacter votre opérateur de téléphonie mobile ou le fabricant de votre appareil.

Informations provenant d' autres sources: exemples d'informations que nous recevons d'autres sources comprennent la livraison et l'adresse de nos transporteurs ou d' autres tiers, que nous utilisons pour corriger nos dossiers et livrer votre prochain achat ou de communication plus facilement mis à jour; les informations de compte, l' achat ou l' information de rachat, et la page d'afficher des informations de certains commerçants avec lesquels nous exerçons nos activités co-entreprises ou de marque pour lesquels nous fournir une assistance technique, la réalisation, la publicité, ou d' autres services; terme et résultat de la recherche d' informations à partir des recherches effectuées par les fonctions de recherche Web de recherche.
6. Quels sont vos droits?
Si vous êtes préoccupé par vos données, vous avez le droit de demander l'accès aux données personnelles que nous pouvons détenir ou d'un processus de vous. Vous avez le droit de nous demander de corriger toute inexactitude dans vos données gratuitement. A tout moment, vous avez également le droit de nous demander de cesser d'utiliser vos données personnelles à des fins de marketing direct.